// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACP-hNbWo0KrxN4z_sEK3chGMgR5vBxx8',
    appId: '1:930456205610:web:c3b3a88e5bc3aab4960653',
    messagingSenderId: '930456205610',
    projectId: 'auth-project-sample-bd104',
    authDomain: 'auth-project-sample-bd104.firebaseapp.com',
    storageBucket: 'auth-project-sample-bd104.appspot.com',
    measurementId: 'G-42HGDZ61YW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBypDCq5hbSZnvkJK-mHbW8z_VT6a8uVEQ',
    appId: '1:930456205610:android:cccb97262d2a1160960653',
    messagingSenderId: '930456205610',
    projectId: 'auth-project-sample-bd104',
    storageBucket: 'auth-project-sample-bd104.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxJQiir3GZAUtBKVjh6jE_xksWEh1izJo',
    appId: '1:930456205610:ios:48b7095f3ceb8cc7960653',
    messagingSenderId: '930456205610',
    projectId: 'auth-project-sample-bd104',
    storageBucket: 'auth-project-sample-bd104.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxJQiir3GZAUtBKVjh6jE_xksWEh1izJo',
    appId: '1:930456205610:ios:2367f00122cc7865960653',
    messagingSenderId: '930456205610',
    projectId: 'auth-project-sample-bd104',
    storageBucket: 'auth-project-sample-bd104.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
